version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
    on-failure: ABORT
    commands:
      - npm i
  pre_build:
    on-failure: ABORT
    commands:
      - npm run dev
  build:
    on-failure: ABORT
    commands:
      - npm run cypress:run

