version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    on-failure: ABORT
    commands:
      - npm i
      - yum install at-spi2-atk -y
  pre_build:
    on-failure: ABORT
    commands:
      - npm run test
