version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    on-failure: ABORT
    commands:
      - npm i
      - apt-get install -y libatk-bridge2.0-0
  pre_build:
    on-failure: ABORT
    commands:
      - npm run test
