const trackList = [
	"complete/",
	"complete/#Dirtybird/",
	"complete/#Dirtybird/087. Walker & Royce - Warkin It (Original Mix).mp3",
	"complete/#Dirtybird/10. San Frandisco (Walker & Royce Extended Remix).mp3",
	"complete/#Dirtybird/walker & royce - word (original mix).mp3",
	"complete/'64-'95/",
	"complete/'64-'95/01 It Was....mp3",
	"complete/'64-'95/02 AKA Come Down On Me.mp3",
	"complete/'64-'95/03 AKA Only Time.mp3",
	"complete/'64-'95/04 AKA Don't Stop Now.mp3",
	"complete/'64-'95/05 AKA Make Things Right.mp3",
	"complete/'64-'95/06 AKA the Shouty Track.mp3",
	"complete/'64-'95/07 AKA Stay With You.mp3",
	"complete/'64-'95/08 AKA the Slow Train.mp3",
	"complete/'64-'95/09 AKA a Man Like Me.mp3",
	"complete/'64-'95/10 AKA Go.mp3",
	"complete/(03) trigger - melbourne, australia - big day out festival .mp3",
	"complete/(05) little goblin - melbourne, australia - big day out festival.mp3",
	"complete/(08) fill - melbourne, australia - big day out festival.mp3",
	"complete/(10) nuclear - melbourne, australia - big day out festival.mp3",
	"complete/(1964) A Hard Days Night/",
	"complete/(1964) A Hard Days Night/Beatles - A Hard Day's Night.mp3",
	"complete/(1964) A Hard Days Night/Beatles - And I Love Her.mp3",
	"complete/(1964) A Hard Days Night/Beatles - Any Time At All.mp3",
	"complete/(1964) A Hard Days Night/Beatles - Can't Buy Me Love.mp3",
	"complete/(1964) A Hard Days Night/Beatles - I Should Have Known Better.mp3",
	"complete/(1964) A Hard Days Night/Beatles - I'll Be Back.mp3",
	"complete/(1964) A Hard Days Night/Beatles - I'll Cry Instead.mp3",
	"complete/(1964) A Hard Days Night/Beatles - I'm Happy Just To Dance With You.mp3",
	"complete/(1964) A Hard Days Night/Beatles - If I Fell.mp3",
	"complete/(1964) A Hard Days Night/Beatles - Tell Me Why.mp3",
	"complete/(1964) A Hard Days Night/Beatles - Things We Said Today.mp3",
	"complete/(1964) A Hard Days Night/Beatles - When I Get Home.mp3",
	"complete/(1964) A Hard Days Night/Beatles - You Can't Do That.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - 01 - mystic eyes.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - 02 - if you and i could be as two.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - 03 - little girl.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - 04 - just a little bit.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - 05 - i gave my love a diamond.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - 06 - gloria.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - 07 - you just can't win.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - 08 - go on home baby.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - 09 - don't look back.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - 10 - i like it like that.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - 11 - i'm gonna dress in black.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - 12 - bright lights big city.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - 13 - my little baby.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - 14 - (get your kicks on) route 66.mp3",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison) - front.jpg",
	"complete/(1965) the angry young them (ft. van morrison)/them - the angry young them (ft. van morrison).SFV",
	"complete/(1978) The Scream/",
	"complete/(1978) The Scream/01 Pure.mp3",
	"complete/(1978) The Scream/02 Jigsaw feeling.mp3",
	"complete/(1978) The Scream/03 Overground.mp3",
	"complete/(1978) The Scream/04 Carcass.mp3",
	"complete/(1978) The Scream/05 Helter skelter.mp3",
	"complete/(1978) The Scream/06 Mirage.mp3",
	"complete/(1978) The Scream/07 Metal postcard (mittageisen).mp3",
	"complete/(1978) The Scream/08 Nicotine stain.mp3",
	"complete/(1978) The Scream/09 Suburban relapse.mp3",
	"complete/(1978) The Scream/10 Switch.mp3",
	"complete/(1980) Hawks and Doves/",
	"complete/(1980) Hawks and Doves/Neil Young - Hawks and Doves - 01 - Little Wing.mp3",
	"complete/(1980) Hawks and Doves/Neil Young - Hawks and Doves - 02 - The Old Homestead.mp3",
	"complete/(1980) Hawks and Doves/Neil Young - Hawks and Doves - 03 - Lost In Space.mp3",
	"complete/(1980) Hawks and Doves/Neil Young - Hawks and Doves - 04 - Captain Kennedy.mp3",
	"complete/(1980) Hawks and Doves/Neil Young - Hawks and Doves - 05 - Stayin' Power.mp3",
	"complete/(1980) Hawks and Doves/Neil Young - Hawks and Doves - 06 - Coastline.mp3",
	"complete/(1980) Hawks and Doves/Neil Young - Hawks and Doves - 07 - Union Man.mp3",
	"complete/(1980) Hawks and Doves/Neil Young - Hawks and Doves - 08 - Comin' Apart At Every Nail.mp3",
	"complete/(1980) Hawks and Doves/Neil Young - Hawks and Doves - 09 - Hawks And Doves.mp3",
	"complete/(1992) Tears Roll Down (Greatest Hits 82-92)/",
	"complete/(1992) Tears Roll Down (Greatest Hits 82-92)/01 - Sowing The Seeds Of Love.mp3",
	"complete/(1992) Tears Roll Down (Greatest Hits 82-92)/02 - Everybody Wants To Rule World.mp3",
	"complete/(1992) Tears Roll Down (Greatest Hits 82-92)/03 - Woman In Chains.mp3",
	"complete/(1992) Tears Roll Down (Greatest Hits 82-92)/04 - Shout.mp3",
	"complete/(1992) Tears Roll Down (Greatest Hits 82-92)/05 - Head Over Heels.mp3",
	"complete/(1992) Tears Roll Down (Greatest Hits 82-92)/06 - Mad World.mp3",
	"complete/(1992) Tears Roll Down (Greatest Hits 82-92)/07 - Pale Shelter.mp3",
	"complete/(1992) Tears Roll Down (Greatest Hits 82-92)/08 - I Believe.mp3",
	"complete/(1992) Tears Roll Down (Greatest Hits 82-92)/09 - Laid So Low (Tears Roll Down).mp3",
	"complete/(1992) Tears Roll Down (Greatest Hits 82-92)/10 - Mothers Talk.mp3",
	"complete/(1992) Tears Roll Down (Greatest Hits 82-92)/11 - Change.mp3",
	"complete/(1992) Tears Roll Down (Greatest Hits 82-92)/12 - Advice For The Young At Heart.mp3",
	"complete/(1992) Tears Roll Down (Greatest Hits 82-92)/front.jpg",
]
