name: E2E on Chrome

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.19.0'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./
          browser: chrome
          start: npm run dev
          wait-on: 'http://localhost:3000'
          # record: true
        env:
          BASIC_AUTH_USERS: ${{ secrets.BASIC_AUTH_USERS }}
          PORT: ${{ secrets.PORT }}
