name: E2E on Chrome

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '16.19.0'
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages and run
        run: npm i && npm run dev

      - name: Test
        run: npm run cypress:run
        env:
          BASIC_AUTH_USERS: 'cd3k:password'
          PORT: 3000
          TEST: true
