name: Cypress Test

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
        env:
          BASIC_AUTH_USERS: 'cd3k:password'
          PORT: 3000
          TEST: true
